// todo : this code is generating the reducers and the actions
// watch tutorial 19 and 20 
import {createSlice} from "@reduxjs/toolkit";


// Initial state for the cake slice
const initialState = {
    numberOfCakes: 10,
}

// Creating the cake slice using createSlice
const cakeSlice = createSlice({
    name: "cake",  // Name of the slice
    initialState, // Initial state
    reducers: {
        ordered: (state) => {
            state.numberOfCakes--;
            // Note: Under the hood, Redux Toolkit uses the Immer library for immutability
        },
        restocked: (state, action) => {
            state.numberOfCakes += action.payload;
        }
        // Note: Action creators are automatically generated by Redux Toolkit
    }
});

// todo : reducer and actions are provided by redux toolkit only
export default cakeSlice.reducer;
export const {ordered , restocked} = cakeSlice.actions;
