// todo : this code is generating the reducers and the actions
// watch tutorial 19 and 20 

// Importing the createSlice function from Redux Toolkit
const createSlice = require("@reduxjs/toolkit").createSlice;

// Logging the createSlice function
console.log("this is that: ", createSlice);

// Initial state for the cake slice
const initialState = {
    numberOfCakes: 10,
}

// Creating the cake slice using createSlice
const cakeSlice = createSlice({
    name: "cake",  // Name of the slice
    initialState, // Initial state
    reducers: {
        ordered: (state, action) => {
            // Reducing the number of cakes by 1 when an order is placed
            state.numberOfCakes--;
            // Note: Under the hood, Redux Toolkit uses the Immer library for immutability
        },
        restocked: (state, action) => {
            // Adding the specified number of cakes when restocking
            state.numberOfCakes += action.payload;
        }
        // Note: Action creators are automatically generated by Redux Toolkit
    }
});

// Exporting the reducer function generated by createSlice
module.exports = cakeSlice.reducer;

// Exporting action creators (if needed) - (Note: Check if it's correct)
module.exports.cakeActions =  cakeSlice.actions;
